<a href="https://colab.research.google.com/github/EON-LEE/Course-DeepLearning/blob/main/Week8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 딥러닝 강의 8주차

## Tensorflow 기초

### 0. Tensorflow setting

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.8.2'

Tensorflow GPU 버전 확인

In [2]:
%tensorflow_version 2.x
import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

Found GPU at: /device:GPU:0


### 1. eager execution

In [ ]:
print(tf.executing_eagerly())

True


In [ ]:
a = 1
b = 2
c = tf.math.add(a, b)
print(c)

tf.Tensor(3, shape=(), dtype=int32)


In [ ]:
c.numpy()

3

### 2. Scalar

In [ ]:
import tensorflow as tf

In [ ]:
# 스칼라 정의하기
a = tf.constant(1)
b = tf.constant(2)
print("a:", a)
print("b:", b)

a: tf.Tensor(1, shape=(), dtype=int32)
b: tf.Tensor(2, shape=(), dtype=int32)


In [ ]:
# 랭크 확인하기
print(tf.rank(a))

tf.Tensor(0, shape=(), dtype=int32)


In [ ]:
# 자료형 변환
a = tf.cast(a, tf.float32)
b = tf.cast(b, tf.float32)
print(a.dtype)
print(b.dtype)

<dtype: 'float32'>
<dtype: 'float32'>


In [ ]:
# 덧셈
c = tf.math.add(a, b)
print("result:", c)
print("rank:", tf.rank(c))

result: tf.Tensor(3.0, shape=(), dtype=float32)
rank: tf.Tensor(0, shape=(), dtype=int32)


In [ ]:
# 뺄셈
print( tf.math.subtract(a, b) )

tf.Tensor(-1.0, shape=(), dtype=float32)


In [ ]:
# 곱셈
print( tf.math.multiply(a, b) )

tf.Tensor(2.0, shape=(), dtype=float32)


In [ ]:
# 나눗셈
print( tf.math.divide(a, b) )

tf.Tensor(0.5, shape=(), dtype=float32)


In [ ]:
# 나눗셈 (나머지)
print( tf.math.mod(a, b) )

tf.Tensor(1.0, shape=(), dtype=float32)


In [ ]:
# 나눗셈 (몫)
print( tf.math.floordiv(a, b) )

tf.Tensor(0.0, shape=(), dtype=float32)


### 3. Vector

In [ ]:
# 라이브러리 불러오기
import tensorflow as tf
import numpy as np

# 1차원 배열 정의 
py_list = [10., 20., 30.] # 파이썬 리스트 활용
num_arr = np.array([10., 10., 10.]) # 넘파이 배열 활용

# 텐서 변환
vec1 = tf.constant(py_list, dtype=tf.float32)
vec2 = tf.constant(num_arr, dtype=tf.float32)

# 텐서 출력
print("vec1:", vec1)
print("vec2:", vec2)

vec1: tf.Tensor([10. 20. 30.], shape=(3,), dtype=float32)
vec2: tf.Tensor([10. 10. 10.], shape=(3,), dtype=float32)


In [ ]:
# 랭크 확인
print(tf.rank(vec1))
print(tf.rank(vec2))

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
# 덧셈 함수
add1 = tf.math.add(vec1, vec2)
print("result:", add1)
print("rank:", tf.rank(add1))

result: tf.Tensor([20. 30. 40.], shape=(3,), dtype=float32)
rank: tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
# 덧셈 연산자
add2 = vec1 + vec2
print("result:", add2)
print("rank:", tf.rank(add2))

result: tf.Tensor([20. 30. 40.], shape=(3,), dtype=float32)
rank: tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
# tf.math 모듈 함수
print(tf.math.subtract(vec1, vec2))
print(tf.math.multiply(vec1, vec2))
print(tf.math.divide(vec1, vec2))
print(tf.math.mod(vec1, vec2))
print(tf.math.floordiv(vec1, vec2))

tf.Tensor([ 0. 10. 20.], shape=(3,), dtype=float32)
tf.Tensor([100. 200. 300.], shape=(3,), dtype=float32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


In [ ]:
# 파이썬 연산자
print(vec1 - vec2)
print(vec1 * vec2)
print(vec1 / vec2)
print(vec1 % vec2)
print(vec1 // vec2)

tf.Tensor([ 0. 10. 20.], shape=(3,), dtype=float32)
tf.Tensor([100. 200. 300.], shape=(3,), dtype=float32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


In [ ]:
# 합계 구하기
print ( tf.reduce_sum(vec1) )
print ( tf.reduce_sum(vec2) )

tf.Tensor(60.0, shape=(), dtype=float32)
tf.Tensor(30.0, shape=(), dtype=float32)


In [ ]:
# 거듭제곱
print( tf.math.square(vec1) )

tf.Tensor([100. 400. 900.], shape=(3,), dtype=float32)


In [ ]:
# 거듭제곱 (파이썬 연산자)
print(vec1**2)

tf.Tensor([ 99.99999 400.      899.99994], shape=(3,), dtype=float32)


In [ ]:
# 제곱근
print( tf.math.sqrt(vec2) )

In [ ]:
# 제곱근 (파이썬 연산자)
print( vec2**0.5 )

tf.Tensor([3.1622777 3.1622777 3.1622777], shape=(3,), dtype=float32)


In [ ]:
# 브로드캐스팅 연산 
print (vec1 + 1)

tf.Tensor([11. 21. 31.], shape=(3,), dtype=float32)


### 4. Matrix

In [ ]:
# 2차원 배열 정의
list_of_list = [[10, 20], [30, 40]] 

# 텐서 변환 - constant 함수에 2차원 배열 입력
mat1 = tf.constant(list_of_list)

# 랭크 확인
print("rank:", tf.rank(mat1))

# 텐서 출력
print("mat1:", mat1)

rank: tf.Tensor(2, shape=(), dtype=int32)
mat1: tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)


In [ ]:
# 1차원 벡터 정의
vec1 = tf.constant([1, 0])
vec2 = tf.constant([-1, 2])
                   
# 텐서 변환 - stack 함수로 1차원 배열을 위아래로 쌓기
mat2 = tf.stack([vec1, vec2])

# 랭크 확인
print("rank:", tf.rank(mat2))

# 텐서 출력하기
print("mat2:", mat2)

rank: tf.Tensor(2, shape=(), dtype=int32)
mat2: tf.Tensor(
[[ 1  0]
 [-1  2]], shape=(2, 2), dtype=int32)


In [ ]:
# element-by-element 연산
element_mul = tf.math.multiply(mat1, mat2)
print("result:", element_mul)
print("rank:", tf.rank(element_mul))

result: tf.Tensor(
[[ 10   0]
 [-30  80]], shape=(2, 2), dtype=int32)
rank: tf.Tensor(2, shape=(), dtype=int32)


In [ ]:
# 브로드캐스팅 연산
element_bc = tf.math.multiply(mat1, 3)
print("result:", element_bc)
print("rank:", tf.rank(element_bc))

result: tf.Tensor(
[[ 30  60]
 [ 90 120]], shape=(2, 2), dtype=int32)
rank: tf.Tensor(2, shape=(), dtype=int32)


In [ ]:
# 행렬곱 연산
mat_mul = tf.matmul(mat1, mat2)
print("result:", mat_mul)
print("rank:", tf.rank(mat_mul))

result: tf.Tensor(
[[-10  40]
 [-10  80]], shape=(2, 2), dtype=int32)
rank: tf.Tensor(2, shape=(), dtype=int32)


In [ ]:
# 덧셈 연산
add1 = tf.math.add(mat1, mat2)
print("result:", add1)
print("rank:", tf.rank(add1))

result: tf.Tensor(
[[11 20]
 [29 42]], shape=(2, 2), dtype=int32)
rank: tf.Tensor(2, shape=(), dtype=int32)


In [ ]:
# 덧셈 연산자
add2 = mat1 + mat2
print("result:", add2)
print("rank:", tf.rank(add2))

result: tf.Tensor(
[[11 20]
 [29 42]], shape=(2, 2), dtype=int32)
rank: tf.Tensor(2, shape=(), dtype=int32)


In [ ]:
# 텐서를 넘파이로 변환
np_arr = mat_mul.numpy()
print(type(np_arr))
print(np_arr)

<class 'numpy.ndarray'>
[[-10  40]
 [-10  80]]


### 5. Tensor

In [ ]:
# 2차원 배열 정의
mat1 = [[1, 2, 3, 4], 
        [5, 6, 7, 8]]
 
mat2 = [[9, 10, 11, 12],
        [13, 14, 15, 16]]   

mat3 = [[17, 18, 19, 20],
        [21, 22, 23, 24]]    

# 텐서 변환 - constant 함수에 3차원 배열 입력
tensor1 = tf.constant([mat1, mat2, mat3])

# 랭크 확인
print("rank:", tf.rank(tensor1))

# 텐서 출력
print("tensor1:", tensor1)

rank: tf.Tensor(3, shape=(), dtype=int32)
tensor1: tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)


In [ ]:
# 텐서 변환 - stack 함수로 2차원 배열을 위아래로 쌓기
tensor2 = tf.stack([mat1, mat2, mat3])

# 랭크 확인
print("rank:", tf.rank(tensor2))

# 텐서 출력
print("tensor2:", tensor2)

rank: tf.Tensor(3, shape=(), dtype=int32)
tensor2: tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)


In [ ]:
# 1차원 배열 정의
vec1 = [1, 2, 3, 4] 
vec2 = [5, 6, 7, 8] 
vec3 = [9, 10, 11, 12]  
vec4 = [13, 14, 15, 16] 
vec5 = [17, 18, 19, 20] 
vec6 = [21, 22, 23, 24] 

# 1차원 배열을 원소로 갖는 2차원 배열 정의
arr = [[vec1, vec2],
        [vec3, vec4],
        [vec5, vec6]]

# 텐서 변환
tensor3 = tf.constant(arr)

# 랭크 확인
print("rank:", tf.rank(tensor3))

# 텐서 출력
print("tensor3:", tensor3)

rank: tf.Tensor(3, shape=(), dtype=int32)
tensor3: tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)


In [ ]:
# 랭크-4 텐서 만들기
tensor4 = tf.stack([tensor1, tensor2])

# 랭크 확인
print("rank:", tf.rank(tensor4))

# 텐서 출력
print("tensor4:", tensor4)

rank: tf.Tensor(4, shape=(), dtype=int32)
tensor4: tf.Tensor(
[[[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 10 11 12]
   [13 14 15 16]]

  [[17 18 19 20]
   [21 22 23 24]]]


 [[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 10 11 12]
   [13 14 15 16]]

  [[17 18 19 20]
   [21 22 23 24]]]], shape=(2, 3, 2, 4), dtype=int32)


### 6. Indexing

In [ ]:
# 벡터 정의하기
vec = tf.constant([10, 20, 30, 40, 50])
print(vec)

tf.Tensor([10 20 30 40 50], shape=(5,), dtype=int32)


In [ ]:
print(vec[0])

tf.Tensor(10, shape=(), dtype=int32)


In [ ]:
print(vec[-1])

tf.Tensor(50, shape=(), dtype=int32)


In [ ]:
print(vec[:3])

tf.Tensor([10 20 30], shape=(3,), dtype=int32)


In [ ]:
# 행렬 정의하기
mat = tf.constant([[10, 20, 30], 
                    [40, 50, 60]])

print(mat)

tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)


In [ ]:
print(mat[0, 2])

tf.Tensor(30, shape=(), dtype=int32)


In [ ]:
print(mat[0, :])

tf.Tensor([10 20 30], shape=(3,), dtype=int32)


In [ ]:
print(mat[:, 1])

tf.Tensor([20 50], shape=(2,), dtype=int32)


In [ ]:
print(mat[:, :])

tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)


In [ ]:
# 랭크-3 텐서 정의하기
tensor = tf.constant([
    [[10, 20, 30], 
     [40, 50, 60]],
    [[-10, -20, -30], 
     [-40, -50, -60]],   
])
print(tensor)

tf.Tensor(
[[[ 10  20  30]
  [ 40  50  60]]

 [[-10 -20 -30]
  [-40 -50 -60]]], shape=(2, 2, 3), dtype=int32)


In [ ]:
print(tensor[0, :, :])

tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)


In [ ]:
print(tensor[:, :1, :2])

tf.Tensor(
[[[ 10  20]]

 [[-10 -20]]], shape=(2, 1, 2), dtype=int32)


In [ ]:
print(tensor[:, :2, :2])

tf.Tensor(
[[[ 10  20]
  [ 40  50]]

 [[-10 -20]
  [-40 -50]]], shape=(2, 2, 2), dtype=int32)


### 7. Reshape

In [ ]:
# 랭크-1 텐서 정의하기
tensor = tf.constant(range(0, 24))
print(tensor)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23], shape=(24,), dtype=int32)


In [ ]:
tensor1 = tf.reshape(tensor, [3, 8])
print(tensor1)

tf.Tensor(
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]], shape=(3, 8), dtype=int32)


In [ ]:
tensor2 = tf.reshape(tensor1, [-1, 4])
print(tensor2)

tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]], shape=(6, 4), dtype=int32)


In [ ]:
tensor3 = tf.reshape(tensor2, [-1])
print(tensor3)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23], shape=(24,), dtype=int32)


In [ ]:
tensor4 = tf.reshape(tensor3, [-1, 3, 4])
print(tensor4)

tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]], shape=(2, 3, 4), dtype=int32)


In [ ]:
tensor5 = tf.reshape(tensor4, [3, 2, 4])
print(tensor5)

tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]], shape=(3, 2, 4), dtype=int32)


In [ ]:
tensor6 = tf.reshape(tensor5, [3, 2, 2, 2])
print(tensor6)

tf.Tensor(
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]


 [[[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]], shape=(3, 2, 2, 2), dtype=int32)
